AMNOGnews/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  devise_for :users
  devise_for :skcs
  resources :mains, only: [ :index, :show]
  resources :dashboard, only: [ :index]
end

AMNOGnews/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

AMNOGnews/app/models/main.rb
class Main < ApplicationRecord
end

AMNOGnews/app/models/main_search_term.rb
class MainSearchTerm
    attr_reader :where_clause, :where_args, :order
    def initialize(search_term)
        search_term = search_term.downcase
        @where_clause = ""
        @where_args ={}
        build_for_name_search(search_term)
    end
    
    private
    
        def build_for_name_search(search_term)
            @where_clause << case_insensitive_search(:drug_name)
            @where_args[:drug_name] = starts_with(search_term)
            
            @where_clause << " OR #{case_insensitive_search(:brand_name)}"
            @where_args[:brand_name] = starts_with(search_term)
            
            @where_clause << " OR #{case_insensitive_search(:manufacturer)}"
            @where_args[:manufacturer] = starts_with(search_term)
            
            @where_clause << " OR #{case_insensitive_search(:field_of_application)}"
            @where_args[:field_of_application] = starts_with(search_term)
            
            @order = "drug_name asc"
        end
        
        def starts_with(search_term)
            search_term + "%"
        end
        
        def case_insensitive_search(field_name)
            "lower(#{field_name}) like :#{field_name}"
        end
end

AMNOGnews/app/models/skc.rb
class Skc < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

AMNOGnews/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

AMNOGnews/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_skc!
end

AMNOGnews/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
      @mains = Main.all
      Main.order(:start_procedure)
    end
end

AMNOGnews/app/controllers/mains_controller.rb
class MainsController < ApplicationController
    def index
      @mains = Main.all
    end
    
    def show
        if params[:keywords].present?
            @keywords = params[:keywords]
            main_search_term = MainSearchTerm.new(@keywords)
            @mains = Main.where(
                main_search_term.where_clause,
                main_search_term.where_args).
                order(main_search_term.order)
        else
            @mains = []
        end
    end
end

AMNOGnews/app/helpers/application_helper.rb
module ApplicationHelper
end

AMNOGnews/app/views/dashboard/index.html.erb
<section>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Skc Anmog</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="dashboard">Newsfeed</a></li>
        <li><a href="mains">Data Base</a></li>
        <li><a href="mains/show">Search</a></li>
        <li><a href="#">Contact</a></li>
        <li> <%= link_to "Log Out", destroy_skc_session_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
</section>
<header>
    <h1>
        Welcome to AMNOG news, <%= current_skc.email %>!
    </h1>
</header>
<section>
    <p>
        Future home of AMNOG news' Dashboard
    </p>
<section>
    <% @mains.each do |main| %>
      <details>
          <summary>
            <li>Procedure <%= main.status %> <%= main.start_procedure %></li>
          </summary>
          <ul>Drug : <%= main.drug_name %></ul>
        </details>
    <% end %>
</section>

AMNOGnews/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AMNOGnews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>
    <%= stylesheet_pack_tag "application" %>
  </head>

  <body class="container">
    <% if notice.present? %>
      <aside class="alert alert-info">
        <%= notice %>
      </aside>
    <% end %>
    <% if alert.present? %>
      <aside class="alert alert-danger">
        <%= alert %>
      </aside>
    <% end %>
    <%= yield %>
  </body>
</html>

AMNOGnews/app/views/mains/database.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <title>Skc Newsfeed</title>
  </head>
  <header>
  <section>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
           <a class="navbar-brand" href="#">Skc ANMOG</a>
          </div>
          <ul class="nav navbar-nav">
            <li class="active"><a href="index.html.erb">Newsfeed</a></li>
            <li><a href="database.html.erb">Data Base</a></li>
            <li><a href="show.html.erb">Search</a></li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">Logout</a></li>
          </ul>
        </div>
      </nav>
  </section>
    <h1 class="h2">Data Base</h1>
  </header>

  <section>
      <table class="table table-striped">
          <thead>
              <tr>
                  <th>Number</th>
                  <th>Drug Name</th>
                  <th>Brand Name</th>
                  <th>Manufacturer</th>
                  <th>Field of Application</th>
                  <th>Orphan Drug</th>
              </tr>
          </thead>
          <tbody>
              <% @mains.each do |main| %>
                  <tr>
                      <td><%= main.number %></td>
                      <td><%= main.drug_name %></td>
                      <td><%= main.brand_name %></td>
                      <td><%= main.manufacturer %></td>
                      <td><%= main.field_of_application %></td>
                      <td><%= main.orphan_drug %></td>
                  </tr>
              <% end %>
          </tbody>
      </table>
  </section>
</html>

AMNOGnews/app/views/mains/index.html.erb
<section>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Skc Anmog</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="dashboard">Newsfeed</a></li>
        <li class="active"><a href="mains">Data Base</a></li>
        <li><a href="mains/show">Search</a></li>
        <li><a href="#">Contact</a></li>
        <li> <%= link_to "Log Out", destroy_skc_session_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
</section>

<header>
    <h1 class="h2">Data Base</h1>
</header>

<section>
    <table class="table">
        <thead>
            <tr>
                <th>Number</th>
                <th>Drug Name</th>
                <th>Brand Name</th>
                <th>Manufacturer</th>
                <th>Field of Application</th>
                <th>Orphan Drug</th>
            </tr>
        </thead>
        <tbody>
            <% @mains.each do |main| %>
                <tr>
                    <td><%= main.number %></td>
                    <td><%= main.drug_name %></td>
                    <td><%= main.brand_name %></td>
                    <td><%= main.manufacturer %></td>
                    <td><%= main.field_of_application %></td>
                    <td><%= main.orphan_drug %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</section>

AMNOGnews/app/views/mains/show.html.erb
<section>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Skc Anmog</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="../dashboard">Newsfeed</a></li>
        <li><a href="../mains">Data Base</a></li>
        <li class="active"><a href="show">Search</a></li>
        <li><a href="#">Contact</a></li>
        <li> <%= link_to "Log Out", destroy_skc_session_path, method: :delete %></li>
      </ul>
    </div>
  </nav>
</section>
<header>
    <h1 class="h2">Search</h1>
</header>
<section>

</section>
<section class="search-form">
    <%= form_for :mains, method: :get do |f| %>
        <div class="input-group input-group-lg">
            <%= label_tag :keywords, nil, class: "sr-only" %>
            <%= text_field_tag :keywords, nil,
                placeholder:  "Drug Name, Brand Name, Manufacturer, Field of Application, or Orphan Drug",
                class: "form-control input-lg" %>
            <span class="input-group-btn">
                    <%= submit_tag "Find",
                        class: "btn btn-primary btn-lg" %>
            </span>
        </div>
    <% end %>
</section>
<section class="search-results">
    <header>
        <h1 class="h3">Results</h1>
    </header>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Number</th>
                <th>Drug Name</th>
                <th>Brand Name</th>
                <th>Manufacturer</th>
                <th>Field of Application</th>
                <th>Orphan Drug</th>
            </tr>
        </thead>
        <tbody>
            <% @mains.each do |main| %>
                <tr>
                    <td><%= main.number %></td>
                    <td><%= main.drug_name %></td>
                    <td><%= main.brand_name %></td>
                    <td><%= main.manufacturer %></td>
                    <td><%= main.field_of_application %></td>
                    <td><%= main.orphan_drug %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</section>